### ISSUE TITLE
Update git page

### ISSUE THREAD

**Issue by prasanna1211** [Codebrahma/react-lite-ui#107]
1. Update Readme. Readme should contain how to install, how to use, links for documentation, customization, theming, design guidelines

2. ~~Add how to contribute section~~

3. ~~Add license~~
 
4. Add Top X number of contributors section (Automate it).

**Comment by rishichawda** [comment]
These two can be used for contributors - 

https://github.com/DavidWells/markdown-magic-github-contributors - since already using markdown-magic for build bages ( Reference PR: #149 ).

**or**

https://github.com/jonschlinkert/github-contributors - This also has same kind of implementation. Basically, the markdown-magic's contrib plugin uses this package's implementation.

**Comment by rishichawda** [comment]
@prasanna1211 @KRRISH96 2 and 3 are completed. I guess we can consider 1 as done for now?

**Comment by KRRISH96** [comment]
We can use this

> https://github.com/DavidWells/markdown-magic-github-contributors - since already using markdown-magic for build bages

**Comment by rishichawda** [comment]
I've opened a separate issue on #247 for the remaining task. Closing this now.
